version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine
    container_name: rabbitmq
    restart: always
#    hostname: myRabbitmq  对外IP地址
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

