version: '3.7'
services:
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper:latest
    volumes:
      - ./data:/data
    ports:
      - 2182:2181

  kafka1:
    restart: always
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.60:9092   # 这里IP填写当前服务对外提供  访问的地址
      KAFKA_CREATE_TOPICS: "kafeidou:2:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫kafeidou的topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./kafka-logs:/kafka
    depends_on:
      - zookeeper

  kowl:
    image: quay.io/cloudhut/kowl:v1.1.0
    restart: on-failure
    container_name: kowl
    hostname: kowl
    volumes:
      - ./configs/kowl_config.yaml:/etc/kowl/config.yaml
    ports:
      - "9009:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka1
