version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      MEILI_MASTER_KEY: root          # 密钥
      MEILI_MAX_INDEX_SIZE: 507.7Gb   # 最大索引大小
      MEILI_MAX_UDB_SIZE: 1007.7Gb    # 最大数据库大小
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/data.ms
