version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      MEILI_MASTER_KEY: root
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/data.ms
